"use client"
import Navbar from "@/components/Navbar"; // Pastikan jalur ini benar
import Footer from "@/components/Footer"; // Pastikan jalur ini benar
import localFont from "next/font/local";
import { usePathname } from "next/navigation"; // Import usePathname untuk mengakses path
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Menggunakan useRouter untuk mendapatkan path saat ini
  const pathname = usePathname();

  // Mengecek apakah path mengandung "/admin"
  const isAdminPage = pathname.startsWith('/admin/');

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar dan Footer hanya akan tampil jika bukan di halaman admin */}
        {!isAdminPage && <Navbar />}
        <main>{children}</main>
        {!isAdminPage && <Footer />}
      </body>
    </html>
  );
}
