// app/layout.tsx
import Navbar from "@/components/Navbar";  // Pastikan jalur ini benar
import Footer from "@/components/Footer";  // Pastikan jalur ini benar
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar and Footer are included here */}
        <Navbar />
        <main>{children}</main> {/* This will render the content of the page */}
        <Footer />
      </body>
    </html>
  );
}
